#!/usr/bin/env python3
"""Rebuild contents/ui/components/librewxr-map.html from the vendored widget
glue fragments and the LibreWXR checkout sources.

Usage:
    python3 scripts/build_librewxr_map.py [--librewxr /path/to/LibreWXR]

The KDE-widget glue fragments (shell.html, overrides.css, glue-config.js,
glue-adapter.js, glue-controls.js) are vendored in this repository under
scripts/librewxr-map-src/; the shared viewer engine (viewer-core.js) and
stylesheet (viewer.css) come from the LibreWXR checkout given via
--librewxr (or LIBREWXR_DIR). This script assembles them into the single
self-contained page embedded by the radar tab and writes it in place.
"""

import argparse
import datetime
import os
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
OUT_PATH = os.path.join(REPO_ROOT, "contents", "ui", "components", "librewxr-map.html")
LOCAL_SRC_DIR = os.path.join(SCRIPT_DIR, "librewxr-map-src")

CSS_TOKEN = "/*__VIEWER_CSS__*/"
OVERRIDES_TOKEN = "/*__WIDGET_OVERRIDES_CSS__*/"
CORE_TOKEN = "//__VIEWER_CORE__"
GLUE_CONFIG_TOKEN = "/*@__WIDGET_GLUE_CONFIG__*/"
GLUE_ADAPTER_TOKEN = "/*@__WIDGET_GLUE_ADAPTER__*/"
GLUE_CONTROLS_TOKEN = "/*@__WIDGET_GLUE_CONTROLS__*/"

# Vendored in this repository under scripts/librewxr-map-src/. shell.html is
# the assembly base and carries no token of its own; the remaining fragments
# are substituted at their placeholder tokens.
LOCAL_SOURCES = [
    ("shell.html", None),
    ("overrides.css", OVERRIDES_TOKEN),
    ("glue-config.js", GLUE_CONFIG_TOKEN),
    ("glue-adapter.js", GLUE_ADAPTER_TOKEN),
    ("glue-controls.js", GLUE_CONTROLS_TOKEN),
]

# Relative to the LibreWXR checkout root.
CHECKOUT_SOURCES = [
    ("examples/src/viewer.css", CSS_TOKEN),
    ("examples/src/viewer-core.js", CORE_TOKEN),
]

GENERATED_COMMENT = (
    "<!-- SPDX-License-Identifier: MIT -->\n"
    "<!-- The examples in this directory are licensed under the MIT License. -->\n"
    "<!-- See LICENSE-examples file for the full license text. -->\n"
    "<!-- You are free to copy, modify, and use these files in your own projects under MIT terms. -->\n"
    "<!-- GENERATED by scripts/build_librewxr_map.py - do not edit directly -->"
)


def default_librewxr_dir():
    """Resolve the LibreWXR checkout path: $LIBREWXR_DIR, else the sibling
    LibreWRX directory next to this repo."""
    return os.environ.get("LIBREWXR_DIR") or os.path.join(
        os.path.dirname(REPO_ROOT), "LibreWRX"
    )


def short_head(librewxr_dir):
    """Short HEAD hash of the LibreWXR checkout for the build marker;
    'unknown' outside a git repo or when git is unavailable."""
    try:
        out = subprocess.run(
            ["git", "-C", librewxr_dir, "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if out.returncode == 0:
            return out.stdout.strip() or "unknown"
    except Exception:
        pass  # no git, or git unavailable: fall back to 'unknown'
    return "unknown"


def read_file(path):
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def build_page(librewxr_dir):
    """Assemble the self-contained radar map page from the vendored glue
    fragments and the LibreWXR checkout sources.

    Reads the vendored KDE-widget shell from scripts/librewxr-map-src/ and
    substitutes each source file at its placeholder token, then prepends the
    GENERATED header and the build marker exactly like LibreWXR's
    examples/src/build.py does.
    """
    shell_path = os.path.join(LOCAL_SRC_DIR, "shell.html")
    if not os.path.isfile(shell_path):
        raise SystemExit(
            "error: missing vendored source file 'shell.html' in scripts/librewxr-map-src"
        )
    shell = read_file(shell_path)
    for filename, token in LOCAL_SOURCES[1:]:
        path = os.path.join(LOCAL_SRC_DIR, filename)
        if not os.path.isfile(path):
            raise SystemExit(
                "error: missing vendored source file %r in scripts/librewxr-map-src" % filename
            )
        if token not in shell:
            raise SystemExit("error: shell missing token %r" % token)
        shell = shell.replace(token, read_file(path))
    for relpath, token in CHECKOUT_SOURCES:
        path = os.path.join(librewxr_dir, relpath)
        if not os.path.isfile(path):
            raise SystemExit(
                "error: missing source file %r in the LibreWXR checkout" % relpath
            )
        if token not in shell:
            raise SystemExit("error: shell missing token %r" % token)
        shell = shell.replace(token, read_file(path))

    ts = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    marker = "<!-- librewxr-examples build: %s git:%s -->" % (ts, short_head(librewxr_dir))
    return GENERATED_COMMENT + "\n" + marker + "\n" + shell


def main():
    parser = argparse.ArgumentParser(
        description="Rebuild contents/ui/components/librewxr-map.html from the vendored widget glue fragments and the LibreWXR checkout sources."
    )
    parser.add_argument(
        "--librewxr",
        default=default_librewxr_dir(),
        help="path to a LibreWXR checkout (default: $LIBREWXR_DIR, else the sibling LibreWRX directory)",
    )
    args = parser.parse_args()
    librewxr_dir = args.librewxr

    if not os.path.isdir(librewxr_dir):
        tried = [librewxr_dir]
        env_dir = os.environ.get("LIBREWXR_DIR")
        sibling = os.path.join(os.path.dirname(REPO_ROOT), "LibreWRX")
        if env_dir and env_dir != librewxr_dir:
            tried.append(env_dir)
        if sibling != librewxr_dir:
            tried.append(sibling)
        raise SystemExit(
            "error: LibreWXR checkout not found - tried: %s" % ", ".join(tried)
        )

    page = build_page(librewxr_dir)
    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        fh.write(page)
    print(
        "wrote contents/ui/components/librewxr-map.html (%d bytes) from %s"
        % (os.path.getsize(OUT_PATH), librewxr_dir)
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())